#!/usr/bin/env python3
"""The real 1.20.1 server opens a world holding our Great Pyramid.

The Great Pyramid is an original Ondes VOXEL structure (ondes_voxel:great_pyramid),
not Minecraft content. A vanilla server knows nothing of it: the question is
whether it loads the chunks without losing them, and whether the blocks stay.

  1. ov_gendet --export writes the pyramid's chunks, generated by the server's
     own path (switch on), into .scratch/gp-vanilla/world/region;
  2. the vanilla server is started on that world with the same seed, the
     chunks are force-loaded, saved with `save-all flush`, and it stops;
  3. every block state of every exported chunk is compared, ours against what
     vanilla wrote back, and its log is searched for chunks it refused or
     regenerated and for what it says about the unknown structure id.

    scripts/ovlane.sh java python3 scripts/check_great_pyramid_vanilla.py \
        --seed=<seed> --chunks=x0,z0,x1,z1

Writes .scratch/gp_vanilla.json; deletes the worlds afterwards unless --keep.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from anvil_read import chunks  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PRESET = os.environ.get("OV_PRESET", "macos-debug")
GENDET = ROOT / "build" / PRESET / "bin" / "ov_gendet"
JAVA_HOME = os.environ.get("OV_JAVA_HOME", "/opt/homebrew/opt/openjdk@17")
JAR = ROOT / "tools" / "vanilla" / "server.jar"
RUN = ROOT / ".scratch" / "gp-vanilla"
OUT = ROOT / ".scratch" / "gp_vanilla.json"


def port_open(port: int) -> bool:
    with socket.socket() as s:
        s.settimeout(0.5)
        return s.connect_ex(("127.0.0.1", port)) == 0


def blocks_of(root: dict) -> dict[int, list[str]]:
    """Section y -> 4096 block states as text, `name[k=v,...]`."""
    out: dict[int, list[str]] = {}
    for section in root.get("sections", []):
        states = section.get("block_states")
        if not states:
            continue
        palette = []
        for entry in states["palette"]:
            props = entry.get("Properties")
            text = entry["Name"]
            if props:
                text += "[" + ",".join(f"{k}={props[k]}" for k in sorted(props)) + "]"
            palette.append(text)
        data = states.get("data")
        if not data:
            out[section["Y"]] = [palette[0]] * 4096
            continue
        bits = max(4, (len(palette) - 1).bit_length())
        per = 64 // bits
        mask = (1 << bits) - 1
        cells = []
        for i in range(4096):
            word = data[i // per] & 0xFFFFFFFFFFFFFFFF
            cells.append(palette[(word >> ((i % per) * bits)) & mask])
        out[section["Y"]] = cells
    return out


def read(region_dir: Path) -> dict[tuple[int, int], dict]:
    """Every chunk of a region directory, by its own absolute position.

    `anvil_read.chunks` yields the slot inside the region (0..31), not the
    chunk's position: keyed by that, the chunks of four regions collide.
    """
    found = {}
    for path in sorted(region_dir.glob("r.*.mca")):
        for _, _, root in chunks(str(path)):
            found[(root["xPos"], root["zPos"])] = root
    return found


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--chunks", required=True, help="x0,z0,x1,z1 inclusive")
    parser.add_argument("--port", type=int, default=25618)
    parser.add_argument("--keep", action="store_true")
    # Generation is CPU, the real server is java: run them in their own lanes.
    #   ovlane.sh build python3 … --phase=export
    #   ovlane.sh java  python3 … --phase=vanilla
    parser.add_argument("--phase", choices=["all", "export", "vanilla"], default="all")
    args = parser.parse_args()
    x0, z0, x1, z1 = (int(v) for v in args.chunks.split(","))

    region = RUN / "world" / "region"
    report: dict = {"seed": args.seed, "chunks": [x0, z0, x1, z1]}

    # 1. Ours.
    if args.phase in ("all", "export"):
        shutil.rmtree(RUN, ignore_errors=True)
        region.mkdir(parents=True)
        env = dict(os.environ)
        env.pop("OV_ORIGINAL_STRUCTURES", None)  # the switch stays on: this is the product
        started = time.monotonic()
        subprocess.run([str(GENDET), f"--seed={args.seed}", f"--export={region}",
                        f"--chunks={x0},{z0},{x1},{z1}"], cwd=ROOT, env=env, check=True,
                       stdout=open(RUN / "gendet.log", "w"), stderr=subprocess.STDOUT)
        (RUN / "export_seconds").write_text(str(round(time.monotonic() - started, 1)))
        shutil.copytree(region, RUN / "exported-region")
        if args.phase == "export":
            print(f"exported {len(read(region))} chunks to {region}")
            return 0
    if not (RUN / "exported-region").is_dir():
        raise SystemExit("run --phase=export first")
    report["export_seconds"] = float((RUN / "export_seconds").read_text())
    ours = read(RUN / "exported-region")
    report["exported"] = len(ours)
    ours_blocks = {key: blocks_of(root) for key, root in ours.items()}
    starts = [key for key, root in ours.items()
              if "ondes_voxel:great_pyramid" in root.get("structures", {}).get("starts", {})]
    refs = [key for key, root in ours.items()
            if "ondes_voxel:great_pyramid" in root.get("structures", {}).get("References", {})]
    report["our_start_chunks"] = starts
    report["our_reference_chunks"] = len(refs)
    shutil.copytree(region, RUN / "exported-region")

    # 2. Vanilla.
    server_dir = RUN
    (server_dir / "eula.txt").write_text("eula=true\n")
    (server_dir / "server.properties").write_text("\n".join([
        "online-mode=false", f"level-seed={args.seed}", "level-name=world",
        f"server-port={args.port}", "view-distance=4", "simulation-distance=4",
        "spawn-protection=0", "difficulty=peaceful", "max-players=2", ""]))
    log_path = server_dir / "server.log"
    with open(log_path, "w") as log:
        proc = subprocess.Popen([os.path.join(JAVA_HOME, "bin", "java"), "-Xmx1200M", "-jar",
                                 str(JAR), "nogui"], cwd=server_dir, stdout=log,
                                stderr=subprocess.STDOUT, stdin=subprocess.PIPE)
        try:
            for _ in range(480):
                if port_open(args.port):
                    break
                time.sleep(0.5)
            else:
                raise SystemExit("the vanilla server did not open its port")

            def command(text: str) -> None:
                assert proc.stdin is not None
                proc.stdin.write((text + "\n").encode())
                proc.stdin.flush()

            command(f"forceload add {x0 * 16} {z0 * 16} {x1 * 16 + 15} {z1 * 16 + 15}")
            time.sleep(20)
            command("save-all flush")
            time.sleep(10)
            proc.communicate(b"stop\n", timeout=120)
        except BaseException:
            proc.kill()
            raise
    text = log_path.read_text(errors="replace")
    report["log_errors"] = [line for line in text.splitlines()
                            if ("ERROR" in line or "WARN" in line)
                            and ("chunk" in line.lower() or "structure" in line.lower())][:20]
    report["log_mentions_pyramid"] = [line for line in text.splitlines()
                                      if "ondes_voxel" in line][:10]
    lost = [line for line in text.splitlines()
            if "Couldn't load chunk" in line or "Recreating" in line or "corrupt" in line.lower()]
    report["chunks_lost_lines"] = lost[:10]

    # 3. Compare.
    theirs = read(region)
    compared = differ = missing = 0
    examples = []
    for key, mine in ours_blocks.items():
        root = theirs.get(key)
        if root is None:
            missing += 1
            continue
        other = blocks_of(root)
        for y, cells in mine.items():
            back = other.get(y)
            for i, state in enumerate(cells):
                compared += 1
                seen = back[i] if back else "minecraft:air"
                if seen != state:
                    differ += 1
                    if len(examples) < 10:
                        x = key[0] * 16 + (i & 15)
                        z = key[1] * 16 + ((i >> 4) & 15)
                        examples.append(f"({x}, {y * 16 + (i >> 8)}, {z}): ours {state}, "
                                        f"vanilla {seen}")
    report.update({"cells_compared": compared, "cells_differ": differ, "chunks_missing": missing,
                   "examples": examples,
                   "vanilla_status": sorted({str(r.get("Status")) for r in theirs.values()})})
    OUT.write_text(json.dumps(report, indent=2))
    print(json.dumps(report, indent=2))
    if not args.keep:
        shutil.rmtree(RUN, ignore_errors=True)
    return 0 if differ == 0 and missing == 0 and not lost else 1


if __name__ == "__main__":
    sys.exit(main())
