#!/usr/bin/env python3
"""Structures written by our server's generator, against the game's.

Usage:
  python3 scripts/measure_structures.py <ours-region-dir> <game-region-dir>
          [--witness=<region-dir>] [--kinds=a,b,...]

`ours` is what `ov_gendet --export` wrote: chunks generated by the server's own
GeneratedWorld, structure stage attached, written with world::to_nbt. `game` is
a reference world generated by the real 1.20.1 server. The optional witness is
the same export with OV_STRUCTURES=0: the same terrain without structures, so
the block figure can be read as "what the structure adds".

Three measures, over the chunks both sides have and the game finished:

  1. starts — every start the game stored in a chunk we exported, of the kinds
     we build: found (same name, same start chunk), then piece by piece every
     field, tag type included (a boolean is a byte, the integrity a float);
     plus the starts we stored that the game did not;
  2. References — per chunk and structure, the set of start chunks, ours
     against the game's, restricted to the kinds we build;
  3. blocks — every block state inside the boxes of the game's pieces, ours
     against the game's (and the witness against the game's).

Tag types are compared, never bytes: vanilla orders keys like a HashMap.
"""
import os
import struct
import sys
import zlib
import gzip

sys.path.insert(0, os.path.dirname(__file__))
import anvil_read as A  # noqa: E402

NAMES = {1: "b", 2: "s", 3: "i", 4: "l", 5: "f", 6: "d", 7: "B[]", 8: "str", 9: "list",
         10: "c", 11: "I[]", 12: "L[]"}

BUILT = {"minecraft:igloo", "minecraft:shipwreck", "minecraft:shipwreck_beached",
         "minecraft:ocean_ruin_cold", "minecraft:ocean_ruin_warm", "minecraft:nether_fossil",
         # ── jigsaw ── grown from their pools (docs/provenance/jigsaw.md)
         "minecraft:village_plains", "minecraft:village_desert", "minecraft:village_savanna",
         "minecraft:village_snowy", "minecraft:village_taiga", "minecraft:pillager_outpost",
         "minecraft:bastion_remnant", "minecraft:ancient_city", "minecraft:trail_ruins"}


def tpayload(r, t):
    if t == 9:
        et = r.u1(); n = r.i4()
        return ("list", [tpayload(r, et) for _ in range(n)])
    if t == 10:
        out = {}
        while True:
            ct = r.u1()
            if ct == 0:
                return ("c", out)
            name = r.s()
            out[name] = tpayload(r, ct)
    return (NAMES[t], A.payload(r, t))


def read_region_dir(path, only=None):
    """{(cx, cz): typed root} for every chunk of every region (of `only`, if given)."""
    out = {}
    if not os.path.isdir(path):
        return out
    for name in sorted(os.listdir(path)):
        if not name.endswith(".mca") or (only is not None and name not in only):
            continue
        with open(os.path.join(path, name), "rb") as f:
            raw = f.read()
        if len(raw) < 8192:
            continue
        for idx in range(1024):
            off = struct.unpack(">I", b"\x00" + raw[idx * 4:idx * 4 + 3])[0]
            count = raw[idx * 4 + 3]
            if off == 0 or count == 0:
                continue
            start = off * 4096
            length = struct.unpack(">I", raw[start:start + 4])[0]
            scheme = raw[start + 4]
            body = raw[start + 5:start + 4 + length]
            body = gzip.decompress(body) if scheme == 1 else zlib.decompress(body)
            r = A.R(body)
            r.u1(); r.s()
            root = tpayload(r, 10)[1]
            out[(root["xPos"][1], root["zPos"][1])] = root
    return out


def value(tag):
    return tag[1]


def structures_of(root):
    s = root.get("structures")
    if s is None:
        return {}, {}
    s = s[1]
    starts = value(s.get("starts", ("c", {})))
    refs = value(s.get("References", ("c", {})))
    return starts, refs


def status(root):
    return value(root.get("Status", ("str", "")))


# ── blocks ──

def section_blocks(root):
    """{section y: (palette names, packed longs)}."""
    out = {}
    for sec in value(root.get("sections", ("list", []))):
        sec = sec[1]
        y = value(sec["Y"])
        states = sec.get("block_states")
        if states is None:
            continue
        states = states[1]
        palette = []
        for entry in value(states["palette"]):
            entry = entry[1]
            name = value(entry["Name"])
            props = entry.get("Properties")
            if props is not None:
                name += "[" + ",".join(f"{k}={value(v)}" for k, v in sorted(value(props).items())) + "]"
            palette.append(name)
        data = value(states["data"]) if "data" in states else []
        out[y] = (palette, data)
    return out


class Blocks:
    def __init__(self, chunks):
        self.chunks = chunks
        self.cache = {}

    def at(self, x, y, z):
        key = (x >> 4, z >> 4)
        if key not in self.cache:
            root = self.chunks.get(key)
            self.cache[key] = section_blocks(root) if root is not None else None
        secs = self.cache[key]
        if secs is None:
            return None
        sec = secs.get(y >> 4)
        if sec is None:
            return "minecraft:air"
        palette, data = sec
        if len(palette) == 1:
            return palette[0]
        bits = max(4, (len(palette) - 1).bit_length())
        per = 64 // bits
        index = ((y & 15) * 16 + (z & 15)) * 16 + (x & 15)
        word = data[index // per] & 0xFFFFFFFFFFFFFFFF
        return palette[(word >> ((index % per) * bits)) & ((1 << bits) - 1)]


def compare_fields(game_piece, our_piece, report):
    """Field by field, types included. Returns the number of differences."""
    wrong = 0
    for key in sorted(set(game_piece) | set(our_piece)):
        g = game_piece.get(key)
        o = our_piece.get(key)
        if g == o:
            continue
        wrong += 1
        report.append(f"      {key}: game {g}  ours {o}")
    return wrong


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    opts = dict(a[2:].split("=", 1) for a in sys.argv[1:] if a.startswith("--") and "=" in a)
    ours_dir, game_dir = args[0], args[1]
    kinds = set(opts["kinds"].split(",")) if "kinds" in opts else BUILT
    ours = read_region_dir(ours_dir)
    # Only the game's regions we exported: nothing outside them is compared.
    game = read_region_dir(game_dir, only=set(os.listdir(ours_dir)))
    witness = read_region_dir(opts["witness"]) if "witness" in opts else None
    both = [k for k in ours if k in game and status(game[k]) == "minecraft:full"]
    print(f"chunks exported {len(ours)}, of which the game finished {len(both)}")

    # 1. starts
    found = exact_starts = pieces = exact_pieces = 0
    missing, extra, report = [], [], []
    game_starts = []
    for key in sorted(both):
        g_starts, _ = structures_of(game[key])
        o_starts, _ = structures_of(ours[key])
        for name, start in g_starts.items():
            if name not in kinds:
                continue
            game_starts.append((key, name, start))
            if name not in o_starts:
                missing.append(f"  {name} at chunk {key}: the game has it, we do not")
                continue
            found += 1
            g_children = value(value(start)["Children"])
            o_children = value(value(o_starts[name])["Children"])
            start_ok = len(g_children) == len(o_children)
            if not start_ok:
                report.append(f"  {name} at {key}: {len(g_children)} pieces in the game, "
                              f"{len(o_children)} ours")
            head = value(start)
            for field in ("ChunkX", "ChunkZ", "id", "references"):
                if head.get(field) != value(o_starts[name]).get(field):
                    start_ok = False
                    report.append(f"  {name} at {key}: {field} game {head.get(field)} ours "
                                  f"{value(o_starts[name]).get(field)}")
            for index, (gp, op) in enumerate(zip(g_children, o_children)):
                pieces += 1
                lines = []
                if compare_fields(value(gp), value(op), lines) == 0:
                    exact_pieces += 1
                else:
                    start_ok = False
                    report.append(f"    {name} at {key}, piece {index}:")
                    report.extend(lines)
            exact_starts += 1 if start_ok else 0
        for name in o_starts:
            if name in kinds and name not in g_starts:
                extra.append(f"  {name} at chunk {key}: ours, not the game's")
    print(f"\n1. starts of {sorted(kinds)}")
    print(f"   the game's, in finished exported chunks: {len(game_starts)}")
    print(f"   found by us (same name, same start chunk): {found}")
    print(f"   identical field for field, types included: {exact_starts}")
    print(f"   pieces compared {pieces}, identical {exact_pieces}")
    print(f"   ours and not the game's: {len(extra)}")
    for line in missing + extra + report:
        print(line)

    # 2. References
    agree = differ = 0
    ref_report = []
    for key in sorted(both):
        _, g_refs = structures_of(game[key])
        _, o_refs = structures_of(ours[key])
        for name in sorted((set(g_refs) | set(o_refs)) & kinds):
            g = set(value(g_refs[name])) if name in g_refs else set()
            o = set(value(o_refs[name])) if name in o_refs else set()
            if g == o:
                agree += 1
            else:
                differ += 1
                if len(ref_report) < 20:
                    ref_report.append(f"  chunk {key} {name}: game {sorted(g)} ours {sorted(o)}")
    print(f"\n2. References (chunk, structure) pairs: {agree} agree, {differ} differ")
    for line in ref_report:
        print(line)

    # 3. blocks in the game's piece boxes
    game_blocks, our_blocks = Blocks(game), Blocks(ours)
    witness_blocks = Blocks(witness) if witness is not None else None
    print("\n3. blocks inside the game's piece boxes (both sides finished)")
    totals = {}
    for key, name, start in game_starts:
        seen = set()
        for piece in value(value(start)["Children"]):
            bb = value(value(piece)["BB"])
            for x in range(bb[0], bb[3] + 1):
                for z in range(bb[2], bb[5] + 1):
                    for y in range(bb[1], bb[4] + 1):
                        seen.add((x, y, z))
        row = totals.setdefault(name, [0, 0, 0, 0])
        for (x, y, z) in seen:
            chunk = (x >> 4, z >> 4)
            if chunk not in game or chunk not in ours or status(game[chunk]) != "minecraft:full":
                continue
            g = game_blocks.at(x, y, z)
            row[0] += 1
            row[1] += 1 if our_blocks.at(x, y, z) == g else 0
            if witness_blocks is not None and chunk in witness:
                row[2] += 1
                row[3] += 1 if witness_blocks.at(x, y, z) == g else 0
    for name, (n, same, wn, wsame) in sorted(totals.items()):
        pct = 100.0 * same / n if n else 0.0
        line = f"   {name:<32} {same:>7} / {n:<7} {pct:7.3f} %"
        if witness_blocks is not None and wn:
            line += f"   witness without structures {wsame} / {wn} {100.0 * wsame / wn:7.3f} %"
        print(line)


if __name__ == "__main__":
    main()
