# Every public header must compile on its own.
#
# A header that quietly relies on whatever its first includer happened to pull
# in works fine until someone includes it first, or until a different standard
# library is used. libc++ drags <string_view> into most of its headers;
# libstdc++ does not — so a missing #include compiles on macOS and fails on
# Linux, which is a slow and annoying way to find out.
#
# This generates one translation unit per public header, containing nothing but
# that header, and compiles them all. It lives in CMake rather than in a CI
# workflow step so that it runs in every build, on every platform, including the
# one the developer is sitting in front of.
set(_ov_header_selftest_template [[// Generated by ov_add_header_selftest. Do not edit.
#include "@relative@"

namespace ov::header_selftest {

int probe_@identifier@() {
    return 0;
}

}  // namespace ov::header_selftest
]])

function(ov_add_header_selftest)
    cmake_parse_arguments(A "" "" "MODULES" ${ARGN})

    set(generated_dir "${CMAKE_BINARY_DIR}/header_selftest")
    file(MAKE_DIRECTORY "${generated_dir}")

    set(sources "")
    set(count 0)

    foreach(module IN LISTS A_MODULES)
        set(include_root "${CMAKE_SOURCE_DIR}/src/${module}/include")
        if(NOT IS_DIRECTORY "${include_root}")
            continue()
        endif()

        file(GLOB_RECURSE headers CONFIGURE_DEPENDS "${include_root}/*.hpp")
        foreach(header IN LISTS headers)
            file(RELATIVE_PATH relative "${include_root}" "${header}")
            string(MAKE_C_IDENTIFIER "${relative}" identifier)
            set(translation_unit "${generated_dir}/selftest_${identifier}.cpp")

            # A translation unit holding only the header would define no symbols,
            # which makes the archiver complain. The unique function also proves
            # the header did not smuggle in a conflicting definition.
            #
            # Built with string(CONFIGURE) on a bracket-quoted template rather
            # than by joining a list: a semicolon in C++ source is a list
            # separator to CMake, so "return 0;" would arrive split in two.
            set(contents "${_ov_header_selftest_template}")
            string(CONFIGURE "${contents}" contents @ONLY)

            # Written only when it would change, so configuring does not force a
            # rebuild of every header check every time.
            set(existing "")
            if(EXISTS "${translation_unit}")
                file(READ "${translation_unit}" existing)
            endif()
            if(NOT existing STREQUAL contents)
                file(WRITE "${translation_unit}" "${contents}")
            endif()

            list(APPEND sources "${translation_unit}")
            math(EXPR count "${count} + 1")
        endforeach()
    endforeach()

    if(NOT sources)
        return()
    endif()

    add_library(ov_header_selftest STATIC ${sources})
    target_link_libraries(ov_header_selftest PRIVATE ${A_MODULES} ov_warnings)
    set_target_properties(ov_header_selftest PROPERTIES FOLDER "checks")

    message(STATUS "Header self-test: ${count} public headers")
endfunction()
